from django.urls import path

from main_app import webhooks
from . import views

urlpatterns = [
    path("admin_dashboard/", views.admin_dashboard, name="admin_dashboard"),

    # Sale & Stock Report (monthly-cycle stock statement) — admin only
    path("stock-report/", views.stock_report_page, name="stock_report"),
    path("stock-report/data/", views.stock_report_data, name="stock_report_data"),
    path("stock-report/generate/", views.stock_report_generate, name="stock_report_generate"),
    path("stock-report/upload-sale/", views.stock_report_upload_sale, name="stock_report_upload_sale"),
    path("stock-report/download/", views.stock_report_download, name="stock_report_download"),
    path("stock-report/download-sale/", views.stock_report_download_sale, name="stock_report_download_sale"),
    path("stock-report/product-options/", views.stock_report_product_options, name="stock_report_product_options"),
    path("stock-report/add-product/", views.stock_report_add_product, name="stock_report_add_product"),
    path("stock-report/remove-product/", views.stock_report_remove_product, name="stock_report_remove_product"),
    path("stock-report/upload-filled/", views.stock_report_upload_filled, name="stock_report_upload_filled"),
    path("stock-report/upload-full/", views.stock_report_upload_full, name="stock_report_upload_full"),
    path("stock-report/submit-damage/", views.stock_report_admin_submit, name="stock_report_admin_submit"),
    path("stock-report/toggle-lock/", views.stock_report_toggle_lock, name="stock_report_toggle_lock"),
    path("", views.loginView, name="login"),
    path("logout/", views.logoutView, name="logout"),
    path("is_authenticated/", views.is_authenticated_view, name="is_authenticated"),
    path("viewRequests/", views.viewRequests, name="view-requests"),
    path('cancel-grn/', views.cancel_grn, name='cancel_grn'),
    # path("do-grn/<path:po_number>/", views.doGRN, name="do-grn"),
    path("dispatch_log_book/", views.dispatch_log_book, name="dispatch_log_book"),
    path("sendToMember", views.sendToMember, name="send-to-member"),
    path("requestSent/", views.requestSent, name="request-sent"),
    path("mailSent/", views.mailSent, name="mail-sent"),
    path("get-employee-name/", views.get_employee_name, name="get_employee_name"),
    path(
        "create-an-indent",
        views.createIndent,
        name="create-an-indent",
    ),
    path(
        "download-indent-template/",
        views.download_indent_template,
        name="download_indent_template",
    ),
    path(
        "import-indent-excel/",
        views.import_indent_excel,
        name="import_indent_excel",
    ),
    path("download-dispatch-excel/", views.download_dispatch_excel, name="download_dispatch_excel"),
    path("create-stn/", views.create_stn, name="create_stn"),
    path("view-stns/", views.view_stns, name="view_stns"),
    path("stn-items/<str:stn_number>/", views.stn_items_json, name="stn_items_json"),
    path("incoming-stns/", views.incoming_stns, name="incoming_stns"),
    path("final-post-stn/<str:stn_number>/", views.final_post_stn, name="final_post_stn"),
    path("download-incoming-stn-excel/<str:stn_number>/", views.download_incoming_stn_excel, name="download_incoming_stn_excel"),
    path("receive-stn/<str:stn_number>/", views.receive_stn, name="receive_stn"),
    path("stn-grn/<str:stn_number>/", views.stn_grn_detail, name="stn_grn_detail"),
    path("download-stn/<str:stn_number>/", views.download_stn_pdf, name="download_stn_pdf"),
    path("download-stn-grn/<str:stn_number>/", views.download_stn_grn_pdf, name="download_stn_grn_pdf"),
    path(
        "viewOthersInventory/", views.viewOthersInventory, name="view_others_inventory"
    ),
    path("GRNdone/", views.GRN_done, name="grn_done"),
    path(
        "ajax/vendor-products/<int:vendor_id>/",
        views.get_vendor_products,
        name="get-vendor-products",
    ),
    path("product_sent/", views.productSent, name="product_sent"),
    # AJAX URL
    path("get_products_by_uom/", views.get_products_by_uom, name="get_products_by_uom"),
    path(
        "get_products_by_uom_for_purchase/",
        views.get_products_by_uom_for_purchase,
        name="get_products_by_uom_for_purchase",
    ),
    path(
        "get-requisition-details/<int:requisition_id>/",
        views.get_requisition_details,
        name="get_requisition_details",
    ),
    path("delete-requisition/", views.delete_requisition, name="delete_requisition"),
    path(
        "update-requisition/<int:requisition_id>/",
        views.update_requisition,
        name="update_requisition",
    ),
    path("hod_requisitions", views.hod_requisitions_view, name="hod_requisitions"),
    path("hod/requisitions/approve-selected/", views.approve_requisitions_bulk, name="approve_requisitions_bulk"),
    path("hod/requisitions/reject-selected/", views.reject_requisitions_bulk, name="reject_requisitions_bulk"),
    path(
        "hod/requisitions/approve/<int:pk>/",
        views.approve_requisition,
        name="approve_requisition",
    ),
    path(
        "hod/requisitions/reject/<int:pk>/",
        views.reject_requisition,
        name="reject_requisition",
    ),
    path("export_excel_view/", views.exportAExcelSheet, name="export_excel_view"),
    path("export-as-excel/", views.export_as_excel_hod, name="export_as_excel"),
    path('get-products-with-inventory/', views.get_products_with_inventory, name='get_products_with_inventory'),
    path("viewInventory/", views.viewInventory, name="view_inventory"),
    path("adjust-inventory/", views.adjust_inventory, name="adjust_inventory"),
    path("get_inventory_count/", views.get_inventory_count, name="get_inventory_count"),
    path(
        "get_dispatch_notification_count/",
        views.get_dispatch_notification_count,
        name="get_dispatch_notification_count",
    ),
    path("hod_approval/", views.hod_approval, name="hod-approval"),
    # path('send-quantity/', views.send_quantity_to_server, name='send_quantity_to_server')
    path("inventory_transfer", views.InventoryTransfer, name="transfer-inventory"),
    path("send-to-mcc/", views.sendToMCC, name="send-to-mcc"),
    path(
        "view_purchase_requisitions",
        views.view_purchase_requisitions,
        name="view_purchase_requisitions",
    ),
    path("get_vendor_email/", views.get_vendor_email, name="get_vendor_email"),
    path(
        "process-transfer/<int:transfer_id>/<str:action>/",
        views.processTransferRequest,
        name="process_transfer",
    ),
    path("send-mail-page/", views.send_mail_page, name="send_mail_page"),
    path("send-mail/<path:vendor>/", views.send_mail_to_vendor, name="send_mail"),
    path('process-excel-template/', views.process_excel_template, name='process_excel_template'),
    path('download-excel-template/', views.download_excel_template, name='download_excel_template'),
    path('fill-excel-template/', views.fill_excel_template_view, name='fill_excel_template'),
    path(
        "reset/<int:user_id>/<str:token>/",
        views.password_reset_confirm_view,
        name="password_reset_confirm",
    ),
    path("reset-password/", views.password_reset_view, name="password_reset"),
    path("search_po/", views.search_po, name="search_po"),
    path(
        "export_excel_purchase/",
        views.export_excel_purchase,
        name="export_excel_purchase",
    ),
    path("send_approval_email/", views.send_approval_email, name="send_approval_email"),
    # urls.py
    path("download_grn/<str:requisition_id>/", views.download_grn, name="download_grn"),
    path("send_grn_email/", views.send_grn_email, name="send_grn_email"),
    path(
        "send_mail_of_grn_animation/",
        views.send_mail_of_grn_animation,
        name="send_mail_of_grn_animation",
    ),
    path("admin/edit-choices/", views.edit_choices, name="edit_choices"),
    path("admin/edit-choices/", views.edit_choices, name="edit_choices"),
    path("finance_dashboard/", views.finance_dashboard, name="finance_dashboard"),
    path("logistic_dashboard/", views.logistic_dashboard, name="logistic_dashboard"),
    path(
        "fetch-finance-data/", views.fetch_finance_data, name="fetch_finance_data"
    ),  # New AJAX URL
    path(
        "export_excel_finance_data_of_grn_chaalan/",
        views.export_excel_finance_data_of_grn_chaalan,
        name="export_excel_finance_data_of_grn_chaalan",
    ),
    # path(
    #     "indent_for_stock_item_from_mcc/",
    #     views.indent_for_stock_item_from_mcc,
    #     name="indent_for_stock_item_from_mcc",
    # ),
    path(
        "process_requisitions", views.process_requisitions, name="process_requisitions"
    ),
    path(
        "dispatch_notifications/",
        views.dispatch_notification_list,
        name="dispatch_notifications",
    ),
    path(
        "dispatch_item/<int:notification_id>/",
        views.dispatch_item,
        name="dispatch_item",
    ),
    path(
        "dispatch_selected_items/",
        views.dispatch_selected_items,
        name="dispatch_selected_items",
    ),
    path(
        "inventory-by-location/",
        views.inventory_by_location,
        name="inventory_by_location",
    ),
    path('download-advance-sale-pdf/<int:sale_id>/', 
         views.download_advance_sale_pdf, 
         name='download_advance_sale_pdf'),
    
    path('check-pdf-status/<int:sale_id>/', 
         views.check_pdf_status, 
         name='check_pdf_status'),
    path("submit_grn/", views.submit_grn, name="submit_grn"),
    path('advance-sale/', views.advance_sale, name='advance-sale'),
    path('download-advance-sale-pdf/<str:unique_code>/', views.download_advance_sale_pdf, name='download-advance-sale-pdf'),
    path('get-bmc-mcc-list/', views.get_bmc_mcc_list, name='get_bmc_mcc_list'),
    # path('get-products-for-sale/', views.get_products_for_sale, name='get_products_for_sale'),
    # path('get-product-filters/', views.get_product_filters, name='get_product_filters'),
    path('document-search-purchase/', views.document_search_purchase, name='document_search_purchase'),
    path('get-pending-pod-advance-sales/', views.get_pending_pod_advance_sales, name='get_pending_pod_advance_sales'),
    path("get-mpp-with-code/", views.get_mpp_with_code, name="get_mpp_with_code"),
    path('upload-advance-sale-pod/', views.upload_advance_sale_pod, name='upload_advance_sale_pod'),
    path('get-inventory-by-location/', views.get_inventory_by_location, name='get_inventory_by_location'),
    path('finance-inventory-by-location/', views.get_finance_inventory_by_location, name='get_finance_inventory_by_location'),
    path('pod-dashboard/', views.pod_dashboard, name='pod_dashboard'),
    path('get-pending-pods/', views.get_pending_pods, name='get_pending_pods'),
    path('upload-pod/', views.upload_pod, name='upload_pod'),
    path('download-sale-template/', views.download_sale_template, name='download_sale_template'),
    path('finance/upload-sale-template/', views.upload_sale_template, name='upload_sale_template'),
    path('get-sale-upload-history/', views.get_sale_upload_history, name='get_sale_upload_history'),
    path('advance-sale-admin/', views.advance_sale_admin, name='advance-sale-admin'),
    path('debug-sap-columns/', views.debug_sap_columns, name='debug_sap_columns'),
    path('inventory/', views.viewInventory, name='view-inventory'),
    path('inventory/product/<int:product_id>/', views.get_product_details, name='get-product-details'),
    path('inventory/product/<int:product_id>/history/', views.get_product_history, name='get-product-history'),
    path('inventory/product/<int:product_id>/update/', views.update_inventory_stock, name='update-inventory-stock'),
    path('inventory/by-location/', views.get_inventory_by_location, name='get-inventory-by-location'),
    path('inventory/finance/by-location/', views.get_finance_inventory_by_location, name='get-finance-inventory-by-location'),
    path("view-pods/", views.view_pods, name="view_pods"),
    path("get-user-pods/", views.get_user_pods, name="get_user_pods"),
    path("download-pod/<int:pod_id>/", views.download_pod, name="download_pod"),
    path("filter-pods/", views.filter_pods, name="filter_pods"),
    path('download-location-report/', views.download_location_report, name='download_location_report'),
    path('download-master-inventory/', views.download_master_inventory, name='download_master_inventory'),
    path('adjust-inventory-quantity/', views.adjust_inventory_quantity, name='adjust_inventory_quantity'),
    path('get-location-products/', views.get_location_products, name='get_location_products'),
    path('upload-mpp-excel/', views.MPPExcelUploadView.as_view(), name='upload_mpp_excel'),
    path('get-mpp-data/', views.MPPDataView.as_view(), name='get_mpp_data'),
    path('update-mpp-data/', views.UpdateMPPDataView.as_view(), name='update_mpp_data'),
    path('download-product-mapping-template/', views.DownloadProductMappingTemplate.as_view(), name='download_product_mapping_template'),
       # Monthly Cycle Management URLs
    path('finance/monthly-cycles/', views.monthly_cycle_management, name='monthly_cycle_management'),
    path('finance/monthly-cycles/create/', views.create_monthly_cycle, name='create_monthly_cycle'),
    path('finance/monthly-cycles/<int:monthly_cycle_id>/add-cycle/', views.add_cycle_to_month, name='add_cycle_to_month'),
    path('finance/cycles/<int:cycle_id>/update-dates/', views.update_cycle_dates, name='update_cycle_dates'),
    path('finance/cycles/<int:cycle_id>/delete/', views.delete_cycle, name='delete_cycle'),
    path('finance/monthly-cycles/<int:monthly_cycle_id>/details/', views.get_monthly_cycle_details, name='get_monthly_cycle_details'),
    path('finance/cycles/month-year/', views.get_cycles_for_month_year, name='get_cycles_for_month_year'),
    path('finance/cycles/available/', views.get_available_cycles, name='get_available_cycles'),
    path('get_available_cycles_for_pod/', views.get_available_cycles_for_pod, name='get_available_cycles_for_pod'),
    # path('create-sample-cycles/', views.create_sample_cycles, name='create_sample_cycles'),
    path('finance/monthly-cycles/<int:monthly_cycle_id>/delete/', views.delete_monthly_cycle, name='delete_monthly_cycle'),
    path('finance/cycles/<int:cycle_id>/get-details/', views.get_cycle_details, name='get_cycle_details'),
    path('finance/cycles/<int:cycle_id>/toggle-status/', views.toggle_cycle_status, name='toggle_cycle_status'),
    path('finance/cycles/<int:cycle_id>/update/', views.update_cycle, name='update_cycle'),
    path('finance/get-next-sap-numbers/', views.get_next_sap_numbers, name='get_next_sap_numbers'),
    path('finance/cycles-for-monthly-cycle/', views.get_cycles_for_monthly_cycle, name='get_cycles_for_monthly_cycle'),
    path('finance/set-active-cycle/', views.set_active_cycle, name='set_active_cycle'),
    path('finance/update-cycle-sap-number/', views.update_cycle_sap_number, name='update_cycle_sap_number'),
    # path('finance/get-cycle-details/<int:cycle_id>/', views.get_cycle_details_by_id, name='get_cycle_details'),
    # In urls.py
    path('finance/cycles/save-new/', views.save_new_cycle, name='save_new_cycle'),
    path('get-active-cycle/', views.get_active_cycle, name='get_active_cycle'),
    path('get-mapped-products/', views.GetMappedProductsView.as_view(), name='get_mapped_products'),
    path('update-mapped-products/', views.UpdateMappedProductsView.as_view(), name='update_mapped_products'),
    
     path('upload-product-mapping-template/', views.UploadProductMappingTemplate.as_view(), name='upload_product_mapping_template'),
    path('upload-batch-status/', views.UploadBatchStatusView.as_view(), name='upload_batch_status'),
    path('processing-errors/', views.ProcessingErrorsView.as_view(), name='processing_errors'),
    path('reconciliation-audit/', views.ReconciliationAuditView.as_view(), name='reconciliation_audit'),
    
    # Legacy endpoint for backward compatibility
    path('process-excel-template/', views.UploadProductMappingTemplate.as_view(), name='process_excel_template'),
    # Vendor-Product Mapping URLs
    path('download-product-vendor-template/', views.DownloadProductVendorMappingTemplate.as_view(), 
        name='download_product_vendor_template'),
    path('upload-product-vendor-template/', views.UploadProductVendorMappingTemplate.as_view(), 
        name='upload_product_vendor_template'),
    path('upload-po-excel-from-sap', views.upload_po_excel_from_sap, name='upload_po_excel_from_sap'),
    path('get-sap-pos-for-requisition/', views.get_sap_pos_for_requisition, name='get_sap_pos_for_requisition'),
    path('get-advance-sale-data-admin/', views.get_advance_sale_data_for_admin, name='get_advance_sale_data_for_admin'),
    path('get-advance-sale-data/', views.get_advance_sale_data, name='get_advance_sale_data'),
    path('webhooks/whatsapp/', webhooks.whatsapp_webhook, name='whatsapp_webhook'),
    
    path('whatsapp/check-registration/', views.check_whatsapp_registration, name='check_whatsapp_registration'),
    path('whatsapp/get-overview/', views.get_whatsapp_overview, name='get_whatsapp_overview'),
    path('whatsapp/get-results/', views.get_whatsapp_results, name='get_whatsapp_results'),
    path('whatsapp/send-test-message/', views.send_test_whatsapp_message, name='send_test_whatsapp_message'),
    path('whatsapp/send-bulk-test-messages/', views.send_bulk_test_whatsapp_messages, name='send_bulk_test_whatsapp_messages'),
    path('whatsapp/download-report/', views.download_whatsapp_report, name='download_whatsapp_report'),
    path('whatsapp/export-mpp-list/', views.export_mpp_list, name='export_mpp_list'),
    path('whatsapp/task-status/<str:task_id>/', views.whatsapp_task_status, name='whatsapp_task_status'),
    path('whatsapp/check-registration/', views.check_whatsapp_registration, name='check_whatsapp_registration'),
    path('whatsapp/send-test-messages/', views.send_whatsapp_test_messages, name='send_whatsapp_test_messages'),
    path('whatsapp-analytics/', views.whatsapp_analytics_dashboard, name='whatsapp_analytics'),
    path('whatsapp-analytics/api/', views.whatsapp_analytics_api, name='whatsapp_analytics_api'),
    path('whatsapp-analytics/detail/', views.whatsapp_message_detail, name='whatsapp_message_detail'),
    path('whatsapp-analytics/export/', views.whatsapp_export_data, name='whatsapp_export_data'),
    path('whatsapp-analytics/send-test/', views.whatsapp_send_test_message, name='whatsapp_send_test_message'),
    path('whatsapp-analytics/insights/', views.whatsapp_get_insights, name='whatsapp_get_insights'),
    path('whatsapp-analytics/data-api/', views.whatsapp_analytics_data_api, name='whatsapp_analytics_data_api'),
    
    # Add this to your urls.py patterns
    path('view-advance-sales/', views.view_advance_sales, name='view_advance_sales'),
    
    # -------post reconcilation sheet------
    path('test-post-sheet/', views.test_post_sheet, name='test_post_sheet'),
    path('download-reconcilation-template/', views.download_reconciliation_template, name='download_reconciliation_template'),
    path('finance/post-reconciliation/', views.test_post_sheet, name='post_final_reconciliation'),
    path('finance/process-reconciliation/', views.process_final_reconciliation, name='process_final_reconciliation'),
    path('finance/reconciliation-sheets/', views.view_reconciliation_sheets, name='view_reconciliation_sheets'),
    path('finance/reconciliation-sheet/<int:sheet_id>/', views.reconciliation_sheet_detail, name='reconciliation_sheet_detail'),
    path('finance/validate-reconciliation/', views.validate_reconciliation_file, name='validate_reconciliation_file'),
    
    # Location user URLs
    path('location/stock-report/', views.location_stock_report, name='location_stock_report'),
    path('location/stock-report/data/', views.location_stock_report_data, name='location_stock_report_data'),
    path('location/stock-report/submit/', views.location_stock_report_submit, name='location_stock_report_submit'),
    path('location/stock-report/download/', views.location_stock_report_download, name='location_stock_report_download'),
    path('location/stock-report/download-sale/', views.location_stock_report_download_sale, name='location_stock_report_download_sale'),
    path('location/reconciliation/', views.view_location_reconciliation, name='view_location_reconciliation'),
    path('location/acknowledge/<int:record_id>/', views.acknowledge_reconciliation, name='acknowledge_reconciliation'),
    path('finance/reconciliation-sheet/<int:sheet_id>/excel/', views.generate_reconciliation_excel, name='generate_reconciliation_excel'),
    
    path('location-balance/', views.location_balance_view, name='location_balance_view'),
    path('location-balance/details/<int:entry_id>/', views.balance_details_view, name='balance_details'),
    path('location-balance/export/', views.export_balance_excel, name='export_balance_excel'),
    path('create_general_sale/<int:mpp_id>/<int:product_id>/<int:quantity>/', views.create_general_sale, name='create_general_sale'),  
    path('location-balance/get-cycles/', views.get_cycles_by_month_year, name='get_cycles_by_month_year'),  
    path('location-balance/get-months-years/', views.get_all_months_years, name='get_all_months_years'),
    path('location-balance/download-excel/', views.download_opening_closing_excel, name='download_opening_closing_excel'),
]
