# Generated by Django 5.1.3 on 2026-06-13 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='employee_code',
            field=models.CharField(choices=[('SH117', 'SH117'), ('SH168', 'SH168'), ('SH119', 'SH119'), ('SH164', 'SH164'), ('SH539', 'SH539'), ('ST48', 'ST48'), ('SH535', 'SH535'), ('SH533', 'SH533'), ('SH536', 'SH536'), ('SH107', 'SH107'), ('SH152', 'SH152'), ('SH269', 'SH269'), ('SH141', 'SH141'), ('SH237', 'SH237'), ('SH59', 'SH59'), ('SH172', 'SH172'), ('SH236', 'SH236'), ('SH198', 'SH198'), ('SH96', 'SH96'), ('SH201', 'SH201'), ('SH207', 'SH207'), ('SH221', 'SH221'), ('SH71', 'SH71'), ('SH56', 'SH56'), ('SH215', 'SH215'), ('SH88', 'SH88'), ('SH242', 'SH242'), ('SH255', 'SH255'), ('SH246', 'SH246'), ('SH28', 'SH28'), ('SH235', 'SH235'), ('SH153', 'SH153'), ('SH250', 'SH250'), ('SH58', 'SH58'), ('SH210', 'SH210'), ('SH109', 'SH109'), ('SH212', 'SH212'), ('SH104', 'SH104'), ('SH17', 'SH17'), ('SH155', 'SH155'), ('SH154', 'SH154'), ('SH175', 'SH175'), ('SH213', 'SH213'), ('SH114', 'SH114'), ('SH195', 'SH195'), ('SH159', 'SH159'), ('SH61', 'SH61'), ('SH202', 'SH202'), ('SH78', 'SH78'), ('SH124', 'SH124'), ('SH55', 'SH55'), ('SH158', 'SH158'), ('SH69', 'SH69'), ('SH100', 'SH100'), ('SH52', 'SH52'), ('SH216', 'SH216'), ('SH260', 'SH260'), ('SH62', 'SH62'), ('SH190', 'SH190'), ('SH238', 'SH238'), ('SH177', 'SH177'), ('SH80', 'SH80'), ('SH196', 'SH196'), ('SH95', 'SH95'), ('SH48', 'SH48'), ('SH67', 'SH67'), ('SH245', 'SH245'), ('SH168', 'SH168'), ('SH239', 'SH239'), ('SH199', 'SH199'), ('SH227', 'SH227'), ('SH160', 'SH160'), ('SH251', 'SH251'), ('SH243', 'SH243'), ('SH145', 'SH145'), ('SH257', 'SH257'), ('SH112', 'SH112'), ('SH167', 'SH167'), ('SH81', 'SH81'), ('SH82', 'SH82'), ('SH223', 'SH223'), ('SH222', 'SH222'), ('SH169', 'SH169'), ('SH113', 'SH113'), ('SH254', 'SH254'), ('SH258', 'SH258'), ('SH224', 'SH224'), ('SH219', 'SH219'), ('SH133', 'SH133'), ('SH247', 'SH247'), ('SH252', 'SH252'), ('SH135', 'SH135'), ('SH105', 'SH105'), ('SH86', 'SH86'), ('SH226', 'SH226'), ('SH200', 'SH200'), ('SH157', 'SH157'), ('SH108', 'SH108'), ('SH240', 'SH240'), ('SH204', 'SH204'), ('SH259', 'SH259'), ('SH193', 'SH193'), ('SH191', 'SH191'), ('SH266', 'SH266'), ('SH268', 'SH268'), ('SH261', 'SH261'), ('SH262', 'SH262'), ('SH263', 'SH263'), ('SH264', 'SH264'), ('SH265', 'SH265'), ('SH270', 'SH270'), ('SH271', 'SH271'), ('SH272', 'SH272'), ('SH273', 'SH273'), ('SH274', 'SH274'), ('SH275', 'SH275'), ('SH276', 'SH276'), ('SH277', 'SH277'), ('SH278', 'SH278'), ('SH279', 'SH279'), ('SH280', 'SH280'), ('SH281', 'SH281'), ('SH282', 'SH282'), ('ST31', 'ST31'), ('ST41', 'ST41'), ('SH176', 'SH176'), ('ST52', 'ST52'), ('SH293', 'SH293')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='location',
            field=models.CharField(choices=[('AKBARPUR', 'AKBARPUR'), ('RAM SANEHI GHAT', 'RAM SANEHI GHAT'), ('SHUKULBAZAR', 'SHUKULBAZAR'), ('MIHIPURWA', 'MIHIPURWA'), ('Badlapur', 'Badlapur'), ('Pratapgarh', 'Pratapgarh'), ('Bahraich', 'Bahraich'), ('Balrampur', 'Balrampur'), ('Colonelganj', 'Colonelganj'), ('Nanpara', 'Nanpara'), ('Raje Sultanpur', 'Raje Sultanpur'), ('AYODHYA H.O', 'AYODHYA H.O'), ('RAEBARELI', 'RAEBARELI')], default='LOCATION NOT PROVIDED', max_length=100),
        ),
        migrations.CreateModel(
            name='StockTransferNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn_number', models.CharField(default='', editable=False, max_length=20, unique=True)),
                ('from_location', models.CharField(max_length=255)),
                ('from_address', models.TextField(blank=True, null=True)),
                ('to_location', models.CharField(max_length=255)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_item', models.CharField(max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('stn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.stocktransfernote')),
            ],
        ),
    ]
