# Generated by Django 5.1.3 on 2026-06-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_purchaserequisition_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfernote',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfernote',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfernote',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfernoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stn_items', to='main_app.product'),
        ),
    ]
