# Generated by Django 5.1.3 on 2026-06-13 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_stocktransfernote_is_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfernote',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfernote',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfernote',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stns', to=settings.AUTH_USER_MODEL),
        ),
    ]
