# Generated by Django 5.1.3 on 2026-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_stocktransfernote_is_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfernote',
            name='grn_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stocktransfernote',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='stn_grn_proofs/'),
        ),
        migrations.AddField(
            model_name='stocktransfernoteitem',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
