# Generated by Django 5.1.3 on 2026-06-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_stocktransfernote_grn_number_stocktransfernote_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfernote',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='stn_grn_receipts/'),
        ),
    ]
