# Generated by Django 5.1.3 on 2026-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_stocktransfernote_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfernoteitem',
            name='rejected_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
