# Generated by Django 5.1.3 on 2026-06-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_stocktransfernoteitem_rejected_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expired_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='scrap_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
