# Generated by Django 5.1.3 on 2026-06-15 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_inventory_damaged_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('MARK_EXPIRED', 'Mark Expired'), ('MARK_DAMAGED', 'Mark Damaged'), ('DISPOSE', 'Dispose / Scrap')], max_length=20)),
                ('source_condition', models.CharField(choices=[('GOOD', 'Good'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('proof', models.ImageField(blank=True, null=True, upload_to='inventory_disposal_proofs/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='main_app.inventory')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
