# Generated by Django 5.1.3 on 2026-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_inventoryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action',
            field=models.CharField(choices=[('GRN', 'Goods Received'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Return'), ('DAMAGE', 'Damage/Loss'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DISPOSED', 'Disposed')], max_length=20),
        ),
    ]
