# Generated by Django 5.1.3 on 2026-06-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_inventoryhistory_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
