# Generated by Django 5.1.3 on 2026-07-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='response_is_base64',
            field=models.BooleanField(default=False),
        ),
    ]
