# Generated by Django 5.1.3 on 2026-07-06 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_idempotencyrecord_response_is_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SALE_UPLOADED', 'Sale Uploaded'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('sale_file', models.FileField(blank=True, max_length=500, null=True, upload_to='stock_reports/sale_uploads/')),
                ('sale_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('sale_rows_total', models.PositiveIntegerField(default=0)),
                ('sale_rows_matched', models.PositiveIntegerField(default=0)),
                ('sale_rows_unmatched', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sale_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_statement', to='main_app.cycle')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_statements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MPPSaleAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant', models.CharField(blank=True, default='', max_length=50)),
                ('sap_mcc_name', models.CharField(blank=True, default='', max_length=150)),
                ('sap_mpp_code', models.CharField(blank=True, default='', max_length=50)),
                ('sap_mpp_name', models.CharField(blank=True, default='', max_length=150)),
                ('sap_material_code', models.CharField(blank=True, default='', max_length=50)),
                ('sap_material_desc', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('matched', models.BooleanField(default=False)),
                ('bmc_or_mcc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpp_sale_aggregates', to='main_app.bmcormcc')),
                ('mpp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpp_sale_aggregates', to='main_app.mppwithcode')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpp_sale_aggregates', to='main_app.product')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpp_sales', to='main_app.stockstatement')),
            ],
            options={
                'indexes': [models.Index(fields=['statement', 'matched'], name='main_app_mp_stateme_0b6071_idx')],
                'unique_together': {('statement', 'sap_mpp_code', 'sap_material_code')},
            },
        ),
        migrations.CreateModel(
            name='StockStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(default=0)),
                ('received', models.IntegerField(default=0)),
                ('stock_transfer', models.IntegerField(default=0)),
                ('mpp_sale', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('expire', models.IntegerField(default=0)),
                ('closing_balance', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bmc_or_mcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_statement_entries', to='main_app.bmcormcc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_statement_entries', to='main_app.product')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main_app.stockstatement')),
            ],
            options={
                'indexes': [models.Index(fields=['statement', 'bmc_or_mcc'], name='main_app_st_stateme_0bcbef_idx')],
                'unique_together': {('statement', 'bmc_or_mcc', 'product')},
            },
        ),
    ]
