# Generated by Django 5.1.3 on 2026-07-07 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_stockstatement_mppsaleaggregate_stockstatemententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatementLocationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_expire_open', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bmc_or_mcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_statement_location_states', to='main_app.bmcormcc')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_states', to='main_app.stockstatement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('statement', 'bmc_or_mcc')},
            },
        ),
    ]
