# Generated by Django 5.1.3 on 2026-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_stockstatementlocationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatemententry',
            name='received_mcc',
            field=models.IntegerField(default=0),
        ),
    ]
