# Generated by Django 5.1.3 on 2026-07-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_stockstatemententry_received_mcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatement',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockstatement',
            name='override_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
