# Generated by Django 5.1.3 on 2026-07-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_stockstatement_is_manual_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='extra_report_products', to='main_app.bmcormcc')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_extra', to='main_app.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
